### PR TITLE
Minor tweak to pass targetNamespace to klipper-helm job

### PR DESCRIPTION
**Pull request by ibrokethecloud**
Related to https://github.com/k3s-io/helm-controller/issues/54

If a helm deploy fails, the current klipper-helm image fails to remove the chart and try again.

This can cause issues for use cases where we want to pass in a few helmChart manifests which may have dependency.

When the chart install fails, the actual uninstall fails since we dont really pass the namespace for deleting the chart when using helm3 based deploys

The PR involves pass a TARGET_NAMESPACE env variable to the klipper-helm job, which can be used for helm3 based cleanup.

Associate klipper-helm PR: https://github.com/k3s-io/klipper-helm/pull/22

### CODE REVIEW

**Comment by brandond** [comment]
Won't this change the default namespace from `default` to `kube-system` since that's where the HelmChart resources usually live?

**Comment by ibrokethecloud** [comment]
If the HelmChart crd doesnt have a targetNamespace set, then the chart is deployed in the same namespace the HelmChart CRD is created in.

By default in K3S we run this in namespaced made so the CRD's are created in the `kube-system` namespace. So if there is no targetNamespace in the spec then the chart is deployed in `kube-system` namespace only.

Hence the idea that we look for `targetNamespace` in the CRD, if none is present then look for the `namespace` on the CRD itself, because that is where the helm chart would have been deployed.

**Comment by brandond** [comment]
> If the HelmChart crd doesnt have a targetNamespace set, then the chart is deployed in the same namespace the HelmChart CRD is created in.

I wasn't aware of that behavior - my expectation would have been that it went into the default namespace as per standard helm behavior. If that's not the case then I have no objections!

**Comment by ibrokethecloud** [comment]
yeah.. that is why the uninstall fails because the klipper-helm passes no NAMESPACE so it tries to remove from default. The other [PR](https://github.com/k3s-io/klipper-helm/pull/22) addresses that too.

**Review by brandond — APPROVED** [review]

**Review by briandowns — APPROVED** [review]

**Pull request merged**
