### PR TITLE
Adding dependabot to keep dockerfiles up to date

### PR DESCRIPTION
**Pull request by matttrach**
This contributes to https://github.com/k3s-io/k3s/issues/7040.

### CODE REVIEW

**Review by brandond — APPROVED** [review]

**Review by macedogm — APPROVED** [review]
LGTM

Have only a few questions:

1. Don't we also want to bump Go deps in [`go.mod`](https://github.com/k3s-io/helm-controller/blob/master/go.mod)?
2. Will UpdateCLI be added later to help bump these packages?
     1. https://github.com/k3s-io/helm-controller/blob/2fb5f947bba961edbefd7e01c70c100064ba95c8/Dockerfile.dapper#L7-L11
     2. If yes, let me know if you need help writing the scripts.

**Comment by matttrach** [comment]
yes, I wanted to make the changes atomic. starting here with dependabot, then I am going to introduce updatecli with a test, then I will definitely connect with you on adding updatecli scripts to update those items, I really appreciate the help!

**Comment by matttrach** [comment]
I don't want to merge this with a failing CI, but the failure seems to be unrelated to this change. 
@brandond, thank you for taking a look at this review, is there anything you can see that I can do to get the CI working for this change?

**Review by dereknola — APPROVED** [review]

**Comment by brandond** [comment]
I'm not sure why the linter is picking up new warnings, but it needs to either be pinned back to an older version that doesn't complain about these warnings, or the warnings need to be addressed. You're welcome to do those here, or in another PR and then rebase this on top of it.

**Comment by brandond** [comment]
I don't love that, but I guess we can remove the ignores and improve the code later.

**Pull request merged**
